/**
 * AgroLens — PDF & WhatsApp Advisory Export Utility
 * Handles WhatsApp sharing and print-to-PDF generation for
 * both Foliar Disease and Crop Growth Stage phenology reports.
 */

// Helper to remove any HTML tags from raw texts
export function stripHtml(html) {
  if (!html) return "";
  const tmp = document.createElement("div");
  tmp.innerHTML = html;
  return tmp.textContent || tmp.innerText || "";
}

// Multilingual advisory headers and labels
export const EXPORT_TRANSLATIONS = {
  en: {
    reportTitle: "AgroLens Agronomic Advisory Report",
    stageReportTitle: "AgroLens Crop Phenology & Advisory Report",
    crop: "Crop",
    condition: "Identified Condition",
    stage: "Growth Phase",
    subStage: "Specific Stage",
    severity: "Severity Level",
    daysToHarvest: "Expected Harvest",
    diagnosisHeader: "Symptoms & Diagnostic Observations",
    treatmentHeader: "Recommended Treatment & Action Plan",
    irrigationHeader: "Water & Irrigation Management",
    fertilizerHeader: "Fertilizer & Soil Nutrition",
    organicHeader: "Eco / Organic Remedy",
    pestWatchHeader: "Vulnerable Pest & Disease Watch",
    priorityHeader: "Priority Farmer Action",
    dateLabel: "Report Date",
    farmerLabel: "Farmer Profile",
    photoLabel: "Field Image",
    gradcamLabel: "Grad-CAM Attention Heatmap",
    footerNotice: "Official Advisory generated by AgroLens AI Agricultural Intelligence. Always verify with local agricultural extension guidelines.",
    whatsappBtn: "Share on WhatsApp",
    pdfBtn: "Export PDF Report"
  },
  ta: {
    reportTitle: "AgroLens பயிர் நோய் மற்றும் பாதுகாப்பு அறிக்கை",
    stageReportTitle: "AgroLens பயிர் வளர்ச்சி பருவ அறிக்கை",
    crop: "பயிர்",
    condition: "கண்டறியப்பட்ட பாதிப்பு",
    stage: "வளர்ச்சி பருவம்",
    subStage: "குறிப்பிட்ட நிலை",
    severity: "பாதிப்பு தீவிரம்",
    daysToHarvest: "அறுவடைக்கு எதிர்பார்க்கப்படும் நாட்கள்",
    diagnosisHeader: "அறிகுறிகள் மற்றும் களக் குறிப்புகள்",
    treatmentHeader: "பரிந்துரைக்கப்படும் சிகிச்சை மற்றும் செயல் திட்டம்",
    irrigationHeader: "நீர்ப்பாசன மேலாண்மை",
    fertilizerHeader: "உர மேலாண்மை மற்றும் மண் ஊட்டச்சத்து",
    organicHeader: "இயற்கை / அங்கக மருத்துவம்",
    pestWatchHeader: "எதிர்பார்க்கப்படும் பூச்சி மற்றும் நோய் பாதுகாப்பு",
    priorityHeader: "விவசாயியின் உடனடி முன்னுரிமை பணி",
    dateLabel: "அறிக்கை தேதி",
    farmerLabel: "விவசாயி சுயவிவரம்",
    photoLabel: "பயிர் புகைப்படம்",
    gradcamLabel: "Grad-CAM வெப்ப வரைபடம்",
    footerNotice: "AgroLens AI விவசாய தளம் மூலம் உருவாக்கப்பட்ட அதிகாரப்பூர்வ ஆலோசனை. உள்ளூர் வேளாண்மை பல்கலைக்கழக பரிந்துரைகளுடன் ஒப்பிட்டு செயல்படுத்தவும்.",
    whatsappBtn: "வாட்ஸ்அப்பில் பகிரவும்",
    pdfBtn: "PDF அறிக்கை பதிவிறக்கு"
  },
  hi: {
    reportTitle: "AgroLens फसल रोग एवं सुरक्षा परामर्श रिपोर्ट",
    stageReportTitle: "AgroLens फसल विकास अवस्था परामर्श रिपोर्ट",
    crop: "फसल",
    condition: "पहचाना गया रोग / स्थिति",
    stage: "विकास अवस्था",
    subStage: "विशिष्ट चरण",
    severity: "गंभीरता स्तर",
    daysToHarvest: "कटाई में शेष दिन",
    diagnosisHeader: "लक्षण और नैदानिक टिप्पणियां",
    treatmentHeader: "अनुशंसित उपचार और कार्य योजना",
    irrigationHeader: "जल एवं सिंचाई प्रबंधन",
    fertilizerHeader: "उर्वरक एवं मृदा पोषण",
    organicHeader: "जैविक उपचार",
    pestWatchHeader: "संभावित कीट एवं रोग निगरानी",
    priorityHeader: "किसान का प्राथमिकता कार्य",
    dateLabel: "रिपोर्ट दिनांक",
    farmerLabel: "किसान विवरण",
    photoLabel: "फसल फोटो",
    gradcamLabel: "Grad-CAM ध्यान हीटमैप",
    footerNotice: "AgroLens AI कृषि मंच द्वारा तैयार परामर्श। स्थानीय कृषि विज्ञान केंद्र के दिशा-निर्देशों के अनुसार अमल करें।",
    whatsappBtn: "व्हाट्सएप पर साझा करें",
    pdfBtn: "PDF रिपोर्ट डाउनलोड करें"
  }
};

/**
 * Generates formatted WhatsApp text message and opens WhatsApp URL
 */
export function shareToWhatsApp(data) {
  const lang = data.language || "en";
  const t = EXPORT_TRANSLATIONS[lang] || EXPORT_TRANSLATIONS.en;
  const isStage = Boolean(data.isStage);

  let msg = `🌿 *${isStage ? t.stageReportTitle : t.reportTitle}*\n`;
  msg += `🌾 *${t.crop}:* ${data.crop || "—"}\n`;

  if (isStage) {
    msg += `🌱 *${t.stage}:* ${data.condition || data.phase || "—"}\n`;
    if (data.subStage) msg += `📍 *${t.subStage}:* ${data.subStage}\n`;
    if (data.daysToHarvest) msg += `⏳ *${t.daysToHarvest}:* ${data.daysToHarvest}\n`;
  } else {
    msg += `🦠 *${t.condition}:* ${data.condition || "—"}\n`;
    if (data.severity) msg += `⚠️ *${t.severity}:* ${data.severity}\n`;
  }

  msg += `---------------------------------\n`;

  if (data.diagnosis) {
    msg += `🔍 *${t.diagnosisHeader}:*\n${stripHtml(data.diagnosis)}\n\n`;
  }
  if (data.treatment) {
    msg += `💡 *${t.treatmentHeader}:*\n${stripHtml(data.treatment)}\n\n`;
  }
  if (data.irrigation) {
    msg += `💧 *${t.irrigationHeader}:*\n${stripHtml(data.irrigation)}\n\n`;
  }
  if (data.fertilizer) {
    msg += `🌱 *${t.fertilizerHeader}:*\n${stripHtml(data.fertilizer)}\n\n`;
  }
  if (data.organic_tip) {
    msg += `🌿 *${t.organicHeader}:*\n${stripHtml(data.organic_tip)}\n\n`;
  }
  if (data.pestWatch) {
    msg += `🛡️ *${t.pestWatchHeader}:*\n${stripHtml(data.pestWatch)}\n\n`;
  }
  if (data.priorityAction) {
    msg += `⚡ *${t.priorityHeader}:*\n${stripHtml(data.priorityAction)}\n\n`;
  }

  msg += `---------------------------------\n`;
  msg += `🌾 ${t.footerNotice}`;

  const url = "https://api.whatsapp.com/send?text=" + encodeURIComponent(msg);
  window.open(url, "_blank");
}

function formatAdvisoryHtml(text) {
  if (!text) return "—";
  if (text.includes("<ul") || text.includes("<li") || text.includes("<p")) {
    return text;
  }
  const lines = text.split("\n").map(l => l.trim()).filter(Boolean);
  if (lines.length > 1) {
    return "<ol>" + lines.map(l => `<li>${l.replace(/^[-*•\d+.]\s*/, "")}</li>`).join("") + "</ol>";
  }
  return `<p>${text}</p>`;
}

/**
 * Generates clean print-ready HTML and triggers browser PDF printing
 */
export function exportToPdf(data) {
  const lang = data.language || "en";
  const t = EXPORT_TRANSLATIONS[lang] || EXPORT_TRANSLATIONS.en;
  const isStage = Boolean(data.isStage);
  const dateStr = data.dateStr || new Date().toLocaleDateString(lang === "ta" ? "ta-IN" : (lang === "hi" ? "hi-IN" : "en-US"), {
    year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit"
  });
  const farmerName = data.farmerName || "AgroLens Farmer";

  const title = isStage ? t.stageReportTitle : t.reportTitle;

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${title} — ${data.crop || "AgroLens"}</title>
<style>
  @page {
    size: A4 portrait;
    margin: 14mm 16mm;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1b2114;
    background: #fff;
    line-height: 1.5;
    font-size: 13px;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .report-wrap {
    max-width: 820px;
    margin: 0 auto;
    padding: 10px;
  }
  .header-bar {
    background: #2d4627;
    color: #f4f1e2;
    padding: 18px 24px;
    border-radius: 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }
  .brand {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 22px;
    font-weight: 800;
    letter-spacing: -0.5px;
  }
  .brand-sub {
    font-size: 11px;
    opacity: 0.85;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    margin-top: 2px;
  }
  .header-meta {
    text-align: right;
    font-size: 11px;
    opacity: 0.9;
    line-height: 1.4;
  }
  .summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-bottom: 20px;
  }
  .sum-card {
    background: #fbfaf4;
    border: 1px solid #e5e0cf;
    border-radius: 8px;
    padding: 10px 14px;
  }
  .sum-label {
    font-size: 10px;
    text-transform: uppercase;
    font-weight: 700;
    color: #636b56;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
  }
  .sum-value {
    font-size: 14px;
    font-weight: 700;
    color: #1b2114;
  }
  .badge-tag {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 99px;
    font-size: 11px;
    font-weight: 700;
    background: #eef2eb;
    color: #2d4627;
  }
  .badge-tag.rust { background: #fee2e2; color: #b91c1c; }
  .badge-tag.stage { background: #ecfdf5; color: #047857; }
  
  .photos-row {
    display: grid;
    grid-template-columns: ${data.gradcamSrc ? "1fr 1fr" : "1fr"};
    gap: 16px;
    margin-bottom: 20px;
  }
  .photo-box {
    border: 1px solid #e5e0cf;
    border-radius: 10px;
    padding: 10px;
    background: #fdfdfc;
    text-align: center;
  }
  .photo-box img {
    max-height: 200px;
    width: 100%;
    object-fit: contain;
    border-radius: 6px;
    display: block;
    margin: 0 auto 6px;
  }
  .photo-cap {
    font-size: 11px;
    font-weight: 600;
    color: #636b56;
  }

  .advisory-section {
    display: grid;
    grid-template-columns: 1fr;
    gap: 12px;
    margin-bottom: 20px;
  }
  .adv-card {
    border: 1px solid #e5e0cf;
    border-radius: 8px;
    padding: 12px 16px;
    background: #fff;
    page-break-inside: avoid;
  }
  .adv-title {
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    margin-bottom: 6px;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .adv-title.green { color: #2d4627; }
  .adv-title.gold { color: #b45309; }
  .adv-title.blue { color: #0369a1; }
  .adv-title.rust { color: #b91c1c; }
  .adv-content {
    font-size: 12px;
    line-height: 1.6;
    color: #2b3322;
  }
  .adv-content ul, .adv-content ol {
    margin-left: 20px;
    margin-top: 4px;
  }
  .adv-content li {
    margin-bottom: 3px;
  }

  .footer-bar {
    border-top: 1.5px dashed #d5cfbd;
    padding-top: 14px;
    margin-top: 24px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 10px;
    color: #636b56;
  }
</style>
</head>
<body>
<div class="report-wrap">
  <!-- Header -->
  <div class="header-bar">
    <div>
      <div class="brand">
        🌿 AgroLens
      </div>
      <div class="brand-sub">${title}</div>
    </div>
    <div class="header-meta">
      <div><b>${t.dateLabel}:</b> ${dateStr}</div>
      <div><b>${t.farmerLabel}:</b> ${farmerName}</div>
      <div><b>System:</b> AI Agronomy Engine</div>
    </div>
  </div>

  <!-- Key Metrics Summary -->
  <div class="summary-grid">
    <div class="sum-card">
      <div class="sum-label">${t.crop}</div>
      <div class="sum-value">${data.crop || "Crop"}</div>
    </div>
    <div class="sum-card">
      <div class="sum-label">${isStage ? t.stage : t.condition}</div>
      <div class="sum-value" style="font-size:13px;">${data.condition || "—"}</div>
    </div>
    <div class="sum-card">
      <div class="sum-label">${isStage ? t.daysToHarvest : t.severity}</div>
      <div class="sum-value">
        ${isStage
          ? `<span class="badge-tag stage">${data.daysToHarvest || "—"}</span>`
          : `<span class="badge-tag rust">${data.severity || "Evaluated"}</span>`
        }
      </div>
    </div>
    <div class="sum-card">
      <div class="sum-label">Diagnostic Status</div>
      <div class="sum-value">
        <span class="badge-tag" style="background:#e0f2fe;color:#0369a1;">Verified</span>
      </div>
    </div>
  </div>

  <!-- Images Row (Leaf Scan & Grad-CAM) -->
  ${(data.imageSrc || data.gradcamSrc) ? `
  <div class="photos-row">
    ${data.imageSrc ? `
      <div class="photo-box">
        <img src="${data.imageSrc}" alt="Crop leaf scan">
        <div class="photo-cap">📸 ${t.photoLabel}</div>
      </div>
    ` : ""}
    ${data.gradcamSrc ? `
      <div class="photo-box">
        <img src="${data.gradcamSrc}" alt="Grad-CAM heatmap">
        <div class="photo-cap">🔥 ${t.gradcamLabel}</div>
      </div>
    ` : ""}
  </div>
  ` : ""}

  <!-- Detailed Advisory Cards -->
  <div class="advisory-section">
    ${data.diagnosis ? `
      <div class="adv-card">
        <div class="adv-title green">🔍 ${t.diagnosisHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.diagnosis)}</div>
      </div>
    ` : ""}

    ${data.treatment ? `
      <div class="adv-card">
        <div class="adv-title gold">💡 ${t.treatmentHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.treatment)}</div>
      </div>
    ` : ""}

    ${data.irrigation ? `
      <div class="adv-card">
        <div class="adv-title blue">💧 ${t.irrigationHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.irrigation)}</div>
      </div>
    ` : ""}

    ${data.fertilizer ? `
      <div class="adv-card">
        <div class="adv-title green">🌱 ${t.fertilizerHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.fertilizer)}</div>
      </div>
    ` : ""}

    ${data.organic_tip ? `
      <div class="adv-card">
        <div class="adv-title green">🌿 ${t.organicHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.organic_tip)}</div>
      </div>
    ` : ""}

    ${data.pestWatch ? `
      <div class="adv-card">
        <div class="adv-title rust">🛡️ ${t.pestWatchHeader}</div>
        <div class="adv-content">${formatAdvisoryHtml(data.pestWatch)}</div>
      </div>
    ` : ""}

    ${data.priorityAction ? `
      <div class="adv-card" style="border-left:4px solid #16a34a;background:#f0fdf4;">
        <div class="adv-title green" style="color:#15803d;">⚡ ${t.priorityHeader}</div>
        <div class="adv-content" style="font-weight:600;">${formatAdvisoryHtml(data.priorityAction)}</div>
      </div>
    ` : ""}
  </div>

  <!-- Footer -->
  <div class="footer-bar">
    <div>${t.footerNotice}</div>
    <div>AgroLens AI &bull; ${new Date().getFullYear()}</div>
  </div>
</div>

<script>
  window.onload = function() {
    setTimeout(function() {
      window.focus();
      window.print();
    }, 450);
  };
</script>
</body>
</html>`;

  // Open print window
  const printWin = window.open("", "_blank");
  if (printWin) {
    printWin.document.open();
    printWin.document.write(html);
    printWin.document.close();
  } else {
    alert("Please allow pop-ups to export the PDF advisory report.");
  }
}
